blank_issues_enabled: false
contact_links:
  - name: Forge Essentials Discord
    url: https://discord.gg/FNRQjmr
    about: Please go here for support, only use Github for Bug Reports / Feature Requests